git:
  commitMessage: "Release ${version}"
npm:
  publish: false
hooks:
  before:init:
    - "CI=true npm t --silent -- --watchAll=false --json --passWithNoTests"
    - "yarn build"
  after:release:
    - "echo Successfully released ${name} v${version} to ${repo.repository}."
plugins:
  "@release-it/keep-a-changelog":
    filename: "CHANGELOG.md"